#!/bin/bash
#skript loob muutujad ja ühendab need üheks lauseks, siis väljastab neid

aasta=2016
president="Kersti Kaljulaid"
lause_keskosa=". aastal valiti Eesti presidendiks "

lause="${aasta}${lause_keskosa}${president}"

echo "$lause"
